-- uuid-ossp 확장 활성화
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 타임존 설정
SET timezone TO 'UTC';

-- 스키마 설정
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS public;

-- 테이블 설정

-- auth.users 테이블: 사용자 인증 정보를 저장
CREATE TABLE IF NOT EXISTS auth.users (
id                  UUID            DEFAULT uuid_generate_v4() PRIMARY KEY,
email               VARCHAR(255)    UNIQUE NOT NULL,
hashed_password     VARCHAR(512)    NOT NULL,
email_verified_at   TIMESTAMP       DEFAULT NULL,
created_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
updated_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
-- 이메일 형식 검증
CONSTRAINT chk_email_format CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}$')
);
CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth.users(email);

-- public.profiles 테이블: 사용자 프로필 정보를 저장
CREATE TABLE IF NOT EXISTS public.profiles (
id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id             UUID            UNIQUE NOT NULL,
display_name        VARCHAR(100)    NOT NULL,
phone_number        VARCHAR(20)     NOT NULL,
created_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
updated_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
-- 전화번호 형식 검증
CONSTRAINT chk_phone_number_format CHECK (phone_number ~ '\+[1-9]\d{1,14}')
);
CREATE INDEX IF NOT EXISTS idx_public_profiles_phone_number ON public.profiles(phone_number);
CREATE INDEX IF NOT EXISTS idx_public_profiles_display_name ON public.profiles(display_name);

-- public.profile_images 테이블: 사용자 프로필 이미지 정보를 저장
CREATE TABLE IF NOT EXISTS public.profile_images (
id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
profile_id          BIGINT          NOT NULL,
image_url           VARCHAR(512)    NOT NULL,
created_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
updated_at          TIMESTAMP       DEFAULT NOW() NOT NULL,
CONSTRAINT fk_profile_id FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
-- 이미지 url 형식 검증
CONSTRAINT chk_image_url_format CHECK (image_url ~ '^(http|https)://')
);
CREATE INDEX IF NOT EXISTS idx_profile_id ON public.profile_images(profile_id);

-- 트리거 설정

--updated_at 업데티트 함수

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS '
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
' LANGUAGE PLPGSQL;

-- auth.users 트리거 생성
CREATE OR REPLACE TRIGGER trg_update_auth_users_updated_at
BEFORE UPDATE ON auth.users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
